# Generated by Django 5.2.4 on 2025-07-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="default.png", upload_to=""),
        ),
    ]
